### ISSUE TITLE
permissions problem

### ISSUE THREAD

**Issue by algol99** [pulponair/eXtplorer-ISPConfig-authentification#2]
I did exactly as described and everything seams to work BUT extplorer runs under apache user and sees nothing in the use /web directory till you manually change the permissions.
Is there any idea how to run extplorer under the current user?
Thank you

**Comment by pulponair** [comment]
Whats your php api?

**Comment by algol99** [comment]
Hello,​
it's a standard ISPConfig api.

As you can notice I'm in the way to get extplorer working with ISPConfig.
As for now the clients can login with thier own credentials but apache runs
the script with the apache id.
P.S. the server is down now and will be up this afternoon.​

С уважением,
Александр

On Wed, May 31, 2017 at 2:32 AM, Nikolas Hagestein <notifications@github.com

**Comment by pulponair** [comment]
Hey Alexander, 

I know its been a while. But that doesnt seem to be related to this project but more a server konfiguriation issue. So closed.

Cheers,
Nikolas
